# Generated by Django 5.1.5 on 2025-03-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_user_created_at_user_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_registration_completed',
            field=models.BooleanField(default=False, verbose_name='Registration Completed'),
        ),
    ]
