# Generated by Django 5.1.5 on 2025-02-03 17:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0005_socialauthentications_delete_googleauthncredential_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialauthentications',
            name='authentication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_authentications', to='UserAuth.authentication'),
        ),
        migrations.CreateModel(
            name='ResetPassword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('challenge', models.CharField(max_length=128, null=True)),
                ('authentication', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='UserAuth.authentication')),
            ],
            options={
                'verbose_name': 'Reset Password',
                'verbose_name_plural': 'Reset Passwords',
                'db_table': 'reset_password',
                'indexes': [models.Index(fields=['authentication'], name='reset_passw_authent_b00050_idx')],
            },
        ),
    ]
