# Generated by Django 5.1.5 on 2025-02-06 02:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0006_alter_socialauthentications_authentication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resetpassword',
            name='expire_in',
            field=models.DurationField(default=datetime.timedelta(seconds=900)),
        ),
    ]
