# Generated by Django 5.1.5 on 2025-03-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0007_resetpassword_expire_in'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webauthncredential',
            old_name='credential_id_byte',
            new_name='credential_public_key',
        ),
        migrations.RemoveField(
            model_name='webauthncredential',
            name='public_key',
        ),
        migrations.RemoveField(
            model_name='webauthncredential',
            name='type',
        ),
        migrations.AddField(
            model_name='webauthncredential',
            name='aaguid',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webauthncredential',
            name='credential_backed_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='webauthncredential',
            name='credential_device_type',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webauthncredential',
            name='transports',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='webauthncredential',
            name='credential_id',
            field=models.BinaryField(),
        ),
    ]
